[keyboard]
name = "keeboard"
product_name = "keeboard ANSI-104"
vendor_id = 0x4b45
product_id = 0x4244
manufacturer = "Dogma"
chip = "esp32s3"
usb_enable = true

[matrix]
row_pins = ["GPIO0", "GPIO1", "GPIO2", "GPIO3", "GPIO4", "GPIO5"]
col_pins = ["GPIO6", "GPIO7", "GPIO8", "GPIO9", "GPIO10", "GPIO11", "GPIO12", "GPIO13", "GPIO14", "GPIO17", "GPIO18", "GPIO21", "GPIO35", "GPIO36", "GPIO37", "GPIO38", "GPIO45", "GPIO46", "GPIO47", "GPIO39", "GPIO48"]
row2col = true

[layout]
rows = 6
cols = 21
map = """
(0,0)  (0,1)  (0,2)  (0,3)  (0,4)  (0,5)  (0,6)  (0,7)  (0,8)  (0,9)  (0,10) (0,11) (0,12) (0,13) (0,14) (0,15) (0,16) (0,17) (0,18) (0,19) (0,20)
(1,0)  (1,1)  (1,2)  (1,3)  (1,4)  (1,5)  (1,6)  (1,7)  (1,8)  (1,9)  (1,10) (1,11) (1,12) (1,13) (1,14) (1,15) (1,16) (1,17) (1,18) (1,19) (1,20)
(2,0)  (2,1)  (2,2)  (2,3)  (2,4)  (2,5)  (2,6)  (2,7)  (2,8)  (2,9)  (2,10) (2,11) (2,12) (2,13) (2,14) (2,15) (2,16) (2,17) (2,18) (2,19) (2,20)
(3,0)  (3,1)  (3,2)  (3,3)  (3,4)  (3,5)  (3,6)  (3,7)  (3,8)  (3,9)  (3,10) (3,11) (3,12) (3,13) (3,14) (3,15) (3,16) (3,17) (3,18) (3,19) (3,20)
(4,0)  (4,1)  (4,2)  (4,3)  (4,4)  (4,5)  (4,6)  (4,7)  (4,8)  (4,9)  (4,10) (4,11) (4,12) (4,13) (4,14) (4,15) (4,16) (4,17) (4,18) (4,19) (4,20)
(5,0)  (5,1)  (5,2)  (5,3)  (5,4)  (5,5)  (5,6)  (5,7)  (5,8)  (5,9)  (5,10) (5,11) (5,12) (5,13) (5,14) (5,15) (5,16) (5,17) (5,18) (5,19) (5,20)
"""

[keymap]
layers = 3

[[keymap.layer]]
keys = "ESC F1 F2 F3 F4 F5 F6 F7 F8 F9 F10 F11 F12 PSCR SCRL PAUS _ _ _ _ _ GRV 1 2 3 4 5 6 7 8 9 0 MINS EQL BSPC INS HOME PGUP NLCK PSLS PAST PMNS TAB Q W E R T Y U I O P LBRC RBRC BSLS DEL END PGDN P7 P8 P9 PPLS CAPS A S D F G H J K L SCLN QUOT ENT _ _ _ _ P4 P5 P6 _ _ LSFT Z X C V B N M COMM DOT SLSH RSFT UP _ _ _ P1 P2 P3 PENT LCTL LGUI LALT _ SPC _ _ RALT RGUI RCTL LEFT DOWN RGHT _ _ _ P0 _ PDOT _"

[[keymap.layer]]
keys = "_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _"

[[keymap.layer]]
keys = "_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _"

[ble]
enabled = false

[storage]
enabled = true